### ISSUE TITLE
Refatorar código comum de Slot, Block e Button para uma classe abstrata

### ISSUE THREAD

**Issue by devsanxz** [sanx0153/Java1#1]
**Descrição do Problema:**
Atualmente, as classes `Slot`, `Block` e `Button` possuem métodos e atributos duplicados, o que torna o código redundante e mais difícil de manter. Para melhorar a reutilização de código e a manutenção, precisamos refatorar o código comum para uma classe abstrata que será estendida por essas classes.

**Solução Proposta:**
1. Criar uma classe abstrata `UIComponent` que conterá os atributos e métodos comuns.
2. Mover os atributos e métodos comuns de `Slot`, `Block` e `Button` para `UIComponent`.
3. Modificar `Slot`, `Block` e `Button` para estender `UIComponent`.
4. Remover o código duplicado das classes `Slot`, `Block` e `Button`.

**Detalhes Técnicos:**
- **Atributos Comuns:**
  - `int x, y`
  - `Color color`
- **Métodos Comuns:**
  - `void render()`
  - `void setPosition(int x, int y)`

**Exemplo de Código:**

Classe Abstrata `UIComponent`:
```java
public abstract class UIComponent {
    protected int x, y;
    protected Color color;

    public abstract void render();

    public void setPosition(int x, int y) {
        this.x = x;
        this.y = y;
    }
}

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Created a new abstract class UIComponent to contain common attributes and methods. Modified Block, Button, and Key classes to extend UIComponent and removed duplicated code. Updated imports and adjusted constructors accordingly.

You can review changes in this commit: https://github.com/lkilu6456546/sanx0153-Java1-1/commit/301b780d723002006e7c2210cb4c2a6eca0629e0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
